### ISSUE TITLE
define output path

### ISSUE THREAD

**Issue by yoshuawuyts** [mattdesl/install-if-needed#1]
It would be nice if the output path could be specified. Right now it assumes modules will be installed in `./`. Would you accept a PR that adds this to `install-if-needed` and `spawn-npm-install` ?

**Comment by mattdesl** [comment]
👍 would be good

**Comment by yoshuawuyts** [comment]
Actually an easier path is to just use `process.chdir()`. Saves some complexity ^^. Thanks though!
